# .github/workflows/gpt-translate.yml
name: GPT Translate

on:
  workflow_dispatch:

jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run GPT Translate
        uses: 3ru/gpt-translate@master
        with:
          apikey: "sk-p9reRkbTcnLVm4ITgWy0VNzGIDhFTdPxdEg7OM5H0LNSZVRP"
          basePath: "https://free.gpt.ge"
          model: "gpt-4o-mini"
          inputFiles: "${{ github.workspace }}/.github/workflows/test.md"
          outputFiles: "${{ github.workspace }}/test.md"
          languages: "chinese"
